### ISSUE TITLE
RuntimeError: Parent directory ./earlysave does not exist.

### ISSUE THREAD

**Issue by huqiulan** [Hurongyao/Time#2]
训练时报错：执行命令python main.py --config test.yml --doc ./{dataset} --sequence
Train Epoch: 0 [98560/99286 (99%)]      Loss: 1775.361294
Train Average Loss: 1772.74785672829
 Validation: Average Loss: 1936.5173486788433
early stop change
ERROR - main.py - 2024-09-26 16:09:25,111 - Traceback (most recent call last):
  File "/mnt/workspace/TIMEADDM-main/main.py", line 234, in main
    emb.main()
  File "/mnt/workspace/TIMEADDM-main/TIMEEMB.py", line 88, in main
    early_stopping(val_loss, model,states,early)
  File "/mnt/workspace/TIMEADDM-main/early_stopping.py", line 36, in __call__
    self.savemodel(val_loss, model)
  File "/mnt/workspace/TIMEADDM-main/early_stopping.py", line 85, in savemodel
    torch.save(model.state_dict(), path)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 627, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 501, in _open_zipfile_writer
    return container(name_or_buffer)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 472, in __init__
    super().__init__(torch._C.PyTorchFileWriter(self.name))
RuntimeError: Parent directory ./earlysave does not exist.

**Comment by Hurongyao** [comment]
这个就是提示这个文件夹不存在，你创建一下就好啦

**Comment by huqiulan** [comment]
我创建过，然后又执行：还是报错

**Comment by huqiulan** [comment]
我创建过，然后又重新执行：python main.py --config test.yml --doc ./data/PSM --sequence，还是报错
Train Epoch: 24 [97280/99286 (98%)]     Loss: 1496.575122
Train Epoch: 24 [98560/99286 (99%)]     Loss: 1497.819029
Train Average Loss: 1496.0866209737526
 Validation: Average Loss: 1599.8662286416788
early stop change
EarlyStopping counter: 7 out of 7
************************************************************
best_score=-1595.9313115633308
*******************EMB early stop*********************
END
Diffusion step
Load PSM
ERROR - main.py - 2024-10-09 12:00:25,494 - Traceback (most recent call last):
  File "/mnt/workspace/TIMEADDM-main/main.py", line 241, in main
    runner.lstmz()
  File "/mnt/workspace/TIMEADDM-main/runners/diffusion.py", line 186, in lstmz
    ckpt1 = torch.load(
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 997, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 444, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 425, in __init__
    super().__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: './earlysave/best_newPSM_network.pth'
请问是为什么呢？

**Comment by Hurongyao** [comment]
你刚开始跑的不是PSM数据集吧，这个应该是在数据生成加载模型报的错，你的earlysave保存的应该不是该模型。
